### PR TITLE
Remove nightly configs from rustfmt.toml

### LINKED ISSUE #43: rustfmt.toml is broken on stable
Trying to format using current stable (Rust 1.47.0 and rustfmt 1.4.20-stable) produces the following:

```
Warning: Unknown configuration option `chain_indent`
Warning: Unknown configuration option `fn_call_style`
Warning: Unknown configuration option `fn_call_width`
Warning: Unknown configuration option `reorder_imported_names`
Warning: Unknown configuration option `reorder_imports_in_group`
Error: Decoding config file failed:
unknown variant `Visual`, expected one of `Compressed`, `Tall`, `Vertical` for key `fn_args_layout`
Please check your config file.
```

In general, rustfmt should work without errors or warnings on stable, and we should avoid committing formatting configs that require nightly.

### PR DESCRIPTION
**Pull request by jeff-hiner**
fixes #43

### CODE REVIEW

**Comment by jeff-hiner** [comment]
Resolves https://github.com/zonyitoo/mqtt-rs/issues/43

**Comment by zonyitoo** [comment]
Have you reformatted all files with this new format options?

**Comment by jeff-hiner** [comment]
I haven't yet. This is more of an RFC for the formatting options, I guess. Do you want that in this PR?

**Comment by zonyitoo** [comment]
Hmm, I think it should be included in this PR. Otherwise all subsequence submits will contains a lot of unrelated reformatted codes.

**Comment by jeff-hiner** [comment]
OK. I'll reformat once we've resolved #44

**Comment by jeff-hiner** [comment]
`cargo fmt` applied, as requested. How does this look to you? Any tweaks?

**Comment by zonyitoo** [comment]
lgtm

**Pull request merged**
