### PR TITLE
Update tokio to 0.3.0

### PR DESCRIPTION
**Pull request by damienpontifex**
See https://tokio.rs/blog/2020-10-tokio-0-3 for guide on changes

### CODE REVIEW

**Comment by damienpontifex** [comment]
@zonyitoo would you be able to release this update to crates.io? No new functionality, so maybe as 0.8.2?

**Comment by zonyitoo** [comment]
No. This would break others project if they are also using tokio. Must be 0.9.0.

**Comment by damienpontifex** [comment]
0.9.0 would be great :)

**Comment by zonyitoo** [comment]
Published already.

**Comment by damienpontifex** [comment]
Legend, thank you 👍

**Pull request merged**
