### PR TITLE
'QualityOfService' traits for 'QosWithPacketIdentifier'

### PR DESCRIPTION
**Pull request by kteza1**
Since you are exposing this, is it ok to add these `QualityOfService` traits for `QosWithPacketIdentifier`. This makes my code work.

### CODE REVIEW

**Comment by zonyitoo** [comment]
Good!

**Comment by kteza1** [comment]
Thanks :)

**Comment by zonyitoo** [comment]
Will push it tonight(+8)

**Comment by zonyitoo** [comment]
Already published.

**Comment by kteza1** [comment]
:+1:

**Pull request merged**
